### ISSUE TITLE
How about use the English to write those logs?

### ISSUE THREAD

**Issue by suzp1984** [GEngine-js/GEngine#5]
https://github.com/GEngine-js/GEngine/blob/559a75d95a5edb492c12136a3324a4aa54c4659b/hooks/checkDependency.js#L38

Just a personal stupid suggestion, this project can be more international by using English to write everything, let international dev star your project. It's your project, you can do anything you want, don't worry use Chinese, I'm Chinese.

**Comment by hpugis** [comment]
@suzp1984   this is a good suggestion！We will slowly normalize the code.If you are interested a piece of contributed code is welcome. I will upload the architecture diagram later.

**Comment by suzp1984** [comment]
That's great glory for me to contribute anything. I will commit the translations.
