### ISSUE TITLE
Code indent issue

### ISSUE THREAD

**Issue by suzp1984** [GEngine-js/GEngine#6]
https://github.com/GEngine-js/GEngine/blob/559a75d95a5edb492c12136a3324a4aa54c4659b/src/core/EventDispatcher.ts#L2

I'm a bitch here. Because I like your project, Don't judge me.

Is the code indent here different than others? The code indent uses 2 whitespaces, while other files use `tab`.

**Comment by hpugis** [comment]
@suzp1984 we will add eslint to solve these problems

**Comment by suzp1984** [comment]
wonderful
